name: Generar PDF desde README

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p docs/generados

      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: README.md
          output_dir: docs/generados

      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git add docs/generados
      - run: git commit -m "Actualizar PDF" || exit 0
      - run: git push
